[0m11:31:53.421299 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022597B68C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002259ADACA90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002259AB87710>]}


============================== 11:31:53.426318 | 8bcf1a39-57b6-44e6-b3c0-431055a11c41 ==============================
[0m11:31:53.426318 [info ] [MainThread]: Running with dbt=1.9.5
[0m11:31:53.428314 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\DELL\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init retail_transform', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:31:53.463291 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/DELL/.dbt')}
[0m11:31:53.464291 [info ] [MainThread]: Creating dbt configuration folder at 
[0m11:31:53.467295 [debug] [MainThread]: Starter project path: C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\include\starter_project
[0m11:31:53.538952 [info ] [MainThread]: 
Your new dbt project "retail_transform" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:31:53.540970 [info ] [MainThread]: Setting up your profile.
[0m11:35:09.853556 [info ] [MainThread]: Profile retail_transform written to C:\Users\DELL\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m11:35:09.855073 [debug] [MainThread]: Command `dbt init` succeeded at 11:35:09.855073 after 196.54 seconds
[0m11:35:09.856088 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002259467ECD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225945FD7D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000225945FD810>]}
[0m11:35:09.856088 [debug] [MainThread]: Flushing usage events
[0m11:35:17.177533 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:43:39.189143 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026ED2DE8790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026ED6065F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026ED6065C90>]}


============================== 11:43:39.193692 | c46f080d-ecb4-4d92-a2a0-f1a1511ab41c ==============================
[0m11:43:39.193692 [info ] [MainThread]: Running with dbt=1.9.5
[0m11:43:39.195692 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\DELL\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:43:39.196681 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\Projects\Retail Sales Data Pipeline & Analytics Platform\dbt_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:43:39.197679 [debug] [MainThread]: Command `dbt run` failed at 11:43:39.197679 after 0.10 seconds
[0m11:43:39.198682 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026ED605DF10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026ED6032D50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026ECF829850>]}
[0m11:43:39.198682 [debug] [MainThread]: Flushing usage events
[0m11:43:40.619179 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:47:21.665700 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022C2731EBD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022C27325E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022C273259D0>]}


============================== 11:47:21.670221 | 981a7fc9-fe58-4f74-8249-77f76e691d41 ==============================
[0m11:47:21.670221 [info ] [MainThread]: Running with dbt=1.9.5
[0m11:47:21.671225 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\DELL\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:47:21.672235 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\Projects\Retail Sales Data Pipeline & Analytics Platform\dbt_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:47:21.674222 [debug] [MainThread]: Command `dbt run` failed at 11:47:21.674222 after 0.09 seconds
[0m11:47:21.675232 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022C26D8FF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022C270C7AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022C272F2D50>]}
[0m11:47:21.675232 [debug] [MainThread]: Flushing usage events
[0m11:47:27.193919 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:47:59.742244 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018616B955D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186169B7090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018616C0E810>]}


============================== 11:47:59.747252 | 7c93147f-440b-4d86-8e0c-2077710af5dd ==============================
[0m11:47:59.747252 [info ] [MainThread]: Running with dbt=1.9.5
[0m11:47:59.748761 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\DELL\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:47:59.749776 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path D:\Projects\Retail Sales Data Pipeline & Analytics Platform\dbt_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:47:59.750775 [debug] [MainThread]: Command `dbt run` failed at 11:47:59.750775 after 0.09 seconds
[0m11:47:59.751787 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186103E9990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186103E9850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000186103E9950>]}
[0m11:47:59.752779 [debug] [MainThread]: Flushing usage events
[0m11:48:03.753394 [debug] [MainThread]: An error was encountered while trying to flush usage events
